# Generated by Django 4.2.1 on 2023-05-26 10:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import search_car.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=150, verbose_name='город')),
                ('state', models.CharField(max_length=150, verbose_name='штат')),
                ('zip', models.PositiveIntegerField(verbose_name='индекс')),
                ('width', models.FloatField(verbose_name='широта')),
                ('longitude', models.FloatField(verbose_name='долгота')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(validators=[django.core.validators.MinValueValidator(1),
                                                           django.core.validators.MaxValueValidator(1000)],
                                               verbose_name='вес')),
                ('description', models.CharField(max_length=150, verbose_name='описание')),
                ('delivery',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_delivery',
                                   to='search_car.location', verbose_name='отправка в')),
                ('pick_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_pick_up',
                                              to='search_car.location', verbose_name='отправка из')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5, unique=True, verbose_name='номер машины')),
                ('tonnage', models.IntegerField(validators=[django.core.validators.MinValueValidator(1),
                                                            django.core.validators.MaxValueValidator(1000)],
                                                verbose_name='грузоподъемность')),
                ('location', models.ForeignKey(default=search_car.models.default_location,
                                               on_delete=django.db.models.deletion.CASCADE, related_name='car_location',
                                               to='search_car.location', verbose_name='текущая локация')),
            ],
        ),
    ]
